import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ApolloWrapper } from "@/components/providers/apollo-wrapper";
import { Provider } from "jotai";
import { Toaster } from "sonner";

import { ModuleRegistry, ClientSideRowModelModule } from "ag-grid-community";

import {
  LicenseManager,
  ClipboardModule,
  MenuModule,
  RangeSelectionModule,
  ExcelExportModule,
  StatusBarModule,
  ColumnsToolPanelModule,
  FiltersToolPanelModule,
  SetFilterModule,
} from "ag-grid-enterprise";

import "ag-grid-community/styles/ag-grid.css";
import "ag-grid-community/styles/ag-theme-quartz.css";

ModuleRegistry.registerModules([
  ClientSideRowModelModule,
  ClipboardModule,
  MenuModule,
  RangeSelectionModule,
  ExcelExportModule,
  StatusBarModule,
  ColumnsToolPanelModule,
  FiltersToolPanelModule,
  SetFilterModule,
]);
LicenseManager.setLicenseKey(
  process.env.NEXT_PUBLIC_AG_GRID_LICENSE_KEY || "no_license_key",
);

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <Provider>
          <ApolloWrapper>
            <div className="flex min-h-screen">
              {/*<div className="w-48 bg-slate-800 rounded-tr-2xl rounded-br-2xl"></div>*/}
              <main className="flex-1 overflow-hidden">{children}</main>
            </div>
          </ApolloWrapper>
        </Provider>
      </body>
    </html>
  );
}
